version: '3.2'

services:
  db:
    image: mysql:latest
    command: ['mysqld','--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci','--default-time-zone=+02:00','--default-authentication-plugin=mysql_native_password']
    restart: always
    networks:
      - bpr-network
    ports:
      - '6604:3306'
    env_file:
      - .env-mysql
    environment:
      - TZ=Europe/Kiev
  db-admin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    networks:
      - bpr-network
    ports:
      - '8081:80'
    env_file:
      - .env-mysql
    environment:
      PMA_HOST: db
  bpr-bot:
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - bpr-network
    env_file:
      - .env
    restart: always
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: db
    volumes:
      - ./logs:/app/logs
      - ./telegram-session.storage.json:/app/telegram-session.storage.json
      - ./parser:/app/parser
    depends_on:
      - db
volumes:
  db:
networks:
  bpr-network:
    driver: bridge
