version: '3.2'

services:
  bpr-bot-db:
    image: postgres:latest
    restart: always
    networks:
      - bpr-network
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@bpr-bot-db:${POSTGRES_PORT}/bot_db?schema=public
    ports:
      - '5438:5432'
    volumes:
      - bpr-bot-db:/var/lib/postgresql/data
  bpr-bot:
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - bpr-network
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@bpr-bot-db:${POSTGRES_PORT}/bot_db?schema=public
    restart: always
    ports:
      - "3002:3000"
    volumes:
      - ./logs:/usr/src/app/logs
      - ./telegram-session.storage.json:/usr/src/app/telegram-session.storage.json
      - ./parser:/usr/src/app/parser
    depends_on:
      - bpr-bot-db
volumes:
  bpr-bot-db:
networks:
  bpr-network:
    driver: bridge
