version: '3.2'

services:
  bpr-bot-db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5435:5432'
  bpr-bot:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
    networks:
      - bpr-network
    env_file:
      - .env
    restart: always
    ports:
      - "3002:3000"
    volumes:
      - ./logs:/app/logs
      - ./telegram-session.storage.json:/app/telegram-session.storage.json
      - ./parser:/app/parser
    depends_on:
      - bpr-bot-db
volumes:
  bpr-bot-db:
networks:
  bpr-network:
    driver: bridge
