version: '3.2'

services:
  bpr-bot-db:
    image: mysql:8.0
    command: ['mysqld','--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci','--default-time-zone=+02:00','--default-authentication-plugin=mysql_native_password']
    restart: always
    networks:
      - bpr-network
    ports:
      - '6605:3306'
    env_file:
      - mysql.env
    environment:
      - TZ=Europe/Kiev
  db-admin:
    depends_on:
      - bpr-bot-db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    networks:
      - bpr-network
    ports:
      - '8081:80'
    env_file:
      - mysql.env
    environment:
      PMA_HOST: bpr-bot-db
  bpr-bot:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
    networks:
      - bpr-network
    env_file:
      - .env
    restart: always
    ports:
      - "3002:3000"
    volumes:
      - ./logs:/app/logs
      - ./telegram-session.storage.json:/app/telegram-session.storage.json
      - ./parser:/app/parser
    depends_on:
      - bpr-bot-db
volumes:
  bpr-bot-db:
networks:
  bpr-network:
    driver: bridge
